(define-module (deadbeef)
  #:use-module (gnu packages)
  #:use-module (guix git-download)
  #:use-module (guix licenses)
  #:use-module (guix packages)
  #:use-module (guix build-system glib-or-gtk)
  #:use-module (gnu packages xorg)
  #:use-module (gnu packages pulseaudio)
  #:use-module (gnu packages gtk)
  #:use-module (gnu packages curl)
  #:use-module (guix download)
  #:use-module (gnu packages mp3)
  #:use-module (gnu packages cdrom)
  #:use-module (gnu packages web)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages xiph)
  #:use-module (gnu packages image)
  #:use-module (gnu packages audio)
  #:use-module (gnu packages video)
  #:use-module (gnu packages python-xyz)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages crates-io)
  #:use-module (gnu packages llvm)
  #:use-module (gnu packages assembly)
  #:use-module (gnu packages autotools)
  #:use-module (gnu packages gettext)
  #:use-module (gnu packages pkg-config))

(define-public deadbeef
  (package 
   (name "deadbeef")
   (version "1.8.4")
   (source (origin
            (method git-fetch)
            (uri (git-reference
                  (url "git://github.com/Alexey-Yakovenko/deadbeef.git")
                  (commit version)
                  (recursive? #t)))
            (sha256
             (base32
              "1mwiblsfzlp2jhhj5mfcy84wxfna9nmx2ia0i5l570hnhj3gxpwn"))))
   (build-system glib-or-gtk-build-system)
   
   (arguments '(#:configure-flags '("--enable-silent-rules")
                #:tests? #f))
   (inputs `(("gettext" ,gettext-minimal)
             ("libtool" ,libtool)
             ("intltool" ,intltool)
             ("autoconf" ,autoconf)
             ("automake" ,automake)
             ("pkg-config" ,pkg-config)
             ("libsamplerate" ,libsamplerate)
             ("gtk+" ,gtk+)
             ("jansson" ,jansson)
             ("alsa-lib" ,alsa-lib)
             ("libvorbis" ,libvorbis)
             ("libogg" ,libogg)
             ("curl" ,curl)
             ("imlib2" ,imlib2)
             ("libjpeg-turbo" ,libjpeg-turbo)
             ("libmad" ,libmad)
             ("mpg123" ,mpg123)
             ("flac" ,flac)
             ("wavpack" ,wavpack)
             ("libsndfile" ,libsndfile)
             ("libcdio" ,libcdio)
             ("ffmpeg" ,ffmpeg)
             ("xlib" ,xorg-server)
             ("dbus" ,dbus)
             ("pulseaudio" ,pulseaudio)
             ("faad2" ,faad2)
             ("zlib" ,zlib)
             ("libzip" ,libzip)
             ))
   (synopsis "Modular audio player for desktop operating systems")
   (description "DeaDBeeF (as in 0xDEADBEEF) is a modular audio player for 
 GNU/Linux, *BSD, OpenSolaris, macOS, and other UNIX-like systems.
 +DeaDBeeF lets you play variety of audio formats, convert between them, 
 customize the UI almost any way you want, and use many additional plugins 
 which can extend it even more.")
   (home-page "https://deadbeef.sourceforge.io/")
   (license (list gpl2+ lgpl2.1 zlib))))
